ARG NGINX_VERSION=1.28.0
# Menggunakan base image varian "full"
FROM ghcr.io/11notes/nginx:full-${NGINX_VERSION}

# Menyalin file konfigurasi nginx kustom yang sama
COPY default.conf /nginx/etc/default.conf
