ARG NGINX_VERSION=latest
# Menggunakan base image varian "full"
FROM ghcr.io/11notes/nginx:full-${NGINX_VERSION}

# Menyalin file konfigurasi nginx kustom yang sama
COPY default.conf /nginx/etc/default.conf
COPY ping.conf /nginx/etc/ping.conf
