services:
  nginx-web:
    build: .
    image: banghasan/nginx-web-local
    container_name: nginx-web-test
    restart: unless-stopped
    environment:
      TZ: "Asia/Jakarta"
    ports:
      - "8000:80"
    volumes:
      - "./html:/nginx/var/html"
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/localhealth",
          "http://127.0.0.1:80/health",
          "-I",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
